@startuml
!include .\/Application/Startup.puml
!include .\/Application/StartupDevelopment.puml
!include .\/Application/Program.puml
!include .\/ApplicationUnitTests/UnitTest1.puml
!include .\/Application/Exceptions/InvalidBid.puml
!include .\/Application/Helpers/AutoMapperProfile.puml
!include .\/Application/Services/BrokerService.puml
!include .\/Application/Database/DatabaseContext.puml
!include .\/Application/Controllers/BrokerController.puml
!include .\/Application/Controllers/HealthController.puml
!include .\/Application/Repositories/BrokerRepository.puml
!include .\/Application/States/ResultStates.puml
!include .\/Application/Models/Entities/Result.puml
!include .\/Application/Models/DataTransferObjects/BrokerUpdateDto.puml
!include .\/Application/Models/DataTransferObjects/CompleteProjectDto.puml
!include .\/Application/Models/DataTransferObjects/ResultCreationDto.puml
!include .\/Application/Models/DataTransferObjects/BrokerDto.puml
!include .\/Application/Models/DataTransferObjects/ProjectCompleteDto.puml
!include .\/Application/Models/DataTransferObjects/PaidForResultDto.puml
!include .\/Application/Models/DataTransferObjects/InitializedResultDto.puml
!include .\/lib/utility/Application.Utility/Models/Message.puml
!include .\/lib/utility/Application.Utility/Models/AppSettings.puml
!include .\/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include .\/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include .\/lib/utility/Application.Utility/Startup/Settings.puml
!include .\/lib/utility/Application.Utility/Startup/Security.puml
!include .\/lib/utility/Application.Utility/Startup/Logging.puml
!include .\/lib/utility/Application.Utility/Startup/Cors.puml
!include .\/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include .\/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include .\/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include .\/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include .\/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include .\/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include .\/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Payment/TransferData.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Payment/PaymentClient.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Collaboration/CollaborationClient.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Collaboration/EventData.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Bid/BidClient.puml
!include .\/lib/utility/Application.Utility/ClientLibrary/Bid/BidData.puml
@enduml
